### ISSUE TITLE
prune_txs crashing

### ISSUE THREAD

**Issue by joelreymont** [stegos/stegos#1484] opened 2020-02-04 11:06 UTC
```thread 'tokio-runtime-worker-0' panicked at 'assertion failed: `(left == right)`
  left: `H(51246c3ab4bf9f47c25e97896210e1100d38442353cc01c344435e01614a4fc9)`,
 right: `H(afb2ab580899c58e04e5724798625c1ec53c60699b7aaa734db2593d7122376c)`', wallet/src/storage.rs:408:21
stack backtrace:
   0:        0x10e9fa8e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58693bb6a81982c7
   1:        0x10ea1da40 - core::fmt::write::h517c9dd6c463575c
   2:        0x10e9f46bb - std::io::Write::write_fmt::ha65e597afd22ed3d
   3:        0x10e9fcc73 - std::panicking::default_hook::{{closure}}::h6edb8abf9c97a849
   4:        0x10e9fc97a - std::panicking::default_hook::hbf5f5abc2b30e489
   5:        0x10e9fd3bb - std::panicking::rust_panic_with_hook::h010736b09f81f888
   6:        0x10e9fcf19 - std::panicking::continue_panic_fmt::h60b8af77aa7a5237
   7:        0x10e9fce6f - std::panicking::begin_panic_fmt::hea3051e872681acb
   8:        0x10de8972d - stegos_wallet::storage::AccountDatabase::prune_txs::he4aaee8758b42ab6
   9:        0x10defb676 - <stegos_wallet::UnsealedAccountService as futures::future::Future>::poll::h5fdce59ccccc1ed9
  10:        0x10deff1bd - <stegos_wallet::AccountService as futures::future::Future>::poll::hd57a47601fef36df
  11:        0x10e32a95f - futures::task_impl::Spawn<T>::poll_future_notify::h70c7a9233e8c839a
  12:        0x10e32b8c9 - std::panicking::try::do_call::hac3ab49aae4b5372
zsh: abort      ./stegosd -n mainnet
```

**Comment by rtsisyk** [comment] 2020-02-18 07:21
This problem is probably fixed by the new wallet implementation. Let's merge #1439 and re-test again.

**Comment by vldm** [comment] 2020-07-06 11:04
The initial problem is inconsistency in wallet history, so it looks like duplicate of https://github.com/stegos/stegos/issues/1481

**Closed as completed by vldm** 2020-07-06 11:04 UTC
