### ISSUE TITLE
test::integration::rollback_slashing' panicked

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1121] opened 2019-07-17 10:25 UTC
```
2019-07-17 12:43:51,310 INFO  [stegos_blockchain::blockchain] Registered a micro block: epoch=1, offset=1, block=6d5231d686a8, inputs=0, outputs=1
2019-07-17 12:43:51,310 INFO  [stegos_node] I'm auditor, waiting for the next micro block: epoch=1, offset=2, view_change=0, last_block=6d5231d686a8
2019-07-17 12:43:51,310 DEBUG [stegos_node::test::futures_testing] POLL ONCE MORE
thread 'test::integration::rollback_slashing' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `2`', node/src/test/mod.rs:428:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

https://github.com/stegos/stegos/blob/0f042a2fb5a8dafd0d1901c8f4f14947a971abfe/node/src/test/mod.rs#L428
[test2.log](https://github.com/stegos/stegos/files/3401381/test2.log)

**Comment by vldm** [comment] 2019-07-17 12:19
Its highly possible that this test was caused by the same code, as in:
https://github.com/stegos/stegos/issues/1120

Because we fixing it in #1123 I propose to close this too.

And as future steps, we should make our tests more reproducible https://github.com/stegos/stegos/issues/1124 .

**Closed by vldm** 2019-07-17 12:19 UTC
Labels: bug
